receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include:
      #- /var/log/containers/*.log   # Kubernetes
      # OR
      - /var/lib/docker/containers/*/*.log   # Docker

processors:
  batch:
  # transform:
  #   log_statements:
  #     - context: log
  #       statements:
  #         # 1. This parses the JSON string in the body and creates attributes
  #         - merge_maps(log.attributes, ParseJSON(log.body), "upsert") where IsMatch(log.body, "^\\{")

  #         # 2. This fixes the Grafana display. 
  #         # It replaces "event" with the actual event name (like UPDATE_PROFILE_SUCCESS)
  #         - set(log.body, log.attributes["event"]) where log.attributes["event"] != nil
          
  #         # 3. If "event" is missing, use "message" (but only if body was "event")
  #         - set(log.body, log.attributes["message"]) where log.attributes["message"] != nil and log.body == "event"


exporters:

  debug:
    verbosity: detailed

  otlp_http/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

  otlp_http/tempo:
    endpoint: "http://tempo:4318"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    
    logs:
      receivers: [otlp]
      #processors: [transform, batch]
      processors: [batch]
      exporters: [otlp_http/loki, debug]
