services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./infra/otel/otel-collector-config.yaml:/etc/otelcol/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "4317:4317"
    networks:
      - ykw-network

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./infra/tempo/tempo.yaml:/etc/tempo.yaml
      - ./monitoring/tempo:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - ykw-network

  loki:
    image: grafana/loki:3.2.0
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./infra/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./monitoring/loki:/loki
    ports:
      - "3100:3100"
    networks:
      - ykw-network

  # promtail:
  #   image: grafana/promtail:2.9.0
  #   container_name: promtail
  #   volumes:
  #     - ./logs:/var/log/app
  #     - ./infra/loki/promtail-config.yaml:/etc/promtail/config.yaml
  #     - ./monitoring/promtail:/positions
  #   command: -config.file=/etc/promtail/config.yaml
  #   networks:
  #     - ykw-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - ykw-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    networks:
      - ykw-network

networks:
  ykw-network:
    driver: bridge