# Enable AOF
appendonly yes
appendfsync everysec

# AOF rewrite tuning
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Memory
# maxmemory 256mb
# maxmemory-policy allkeys-lru

# Bind (Docker-safe)
bind 0.0.0.0